spring:
  threads:
    virtual:
      enabled: true

configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ${XTHORE_JWT_BASE64_SECRET}
management:
  metrics:
    export:
      prometheus:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
