eureka:
  instance:
    appname: catalog
    instanceId: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: catalog
  config:
    import:
      - optional:classpath:application-catalog-persistence.properties
  profiles:
    active: #spring.profiles.active#
      group:
        dev:
          - dev
