# R2DBC Configuration for Reactive Database Access
spring.r2dbc.url=${XTHORE_DATASOURCE_ORDER_URL}
spring.r2dbc.username=${SPRING_LIQUIBASE_USER}
spring.r2dbc.password=${SPRING_LIQUIBASE_PASSWORD}

# JDBC Configuration for Liquibase
spring.datasource.url=${XTHORE_DATASOURCE_ORDER_LIQUIBASE_URL}
spring.datasource.username=${SPRING_LIQUIBASE_USER}
spring.datasource.password=${SPRING_LIQUIBASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase Configuration
spring.liquibase.url=${XTHORE_DATASOURCE_ORDER_LIQUIBASE_URL}
spring.liquibase.user=${SPRING_LIQUIBASE_USER}
spring.liquibase.password=${SPRING_LIQUIBASE_PASSWORD}
spring.liquibase.change-log=classpath:liquibase/changelog/order.xml
spring.liquibase.enabled=true
